### ISSUE TITLE
Hackage released version does not build

### ISSUE THREAD

**Issue by ghost** [gilligan/hoobuddy#1]
It seems like the file `Hoobuddy.hs` is missing in the sdist on hackage.
Trying to build the version I got via `cabal unpack hoobuddy` fails with

```
src/Main.hs:18:8:
    Could not find module ‘Hoobuddy’
    Use -v to see a list of the files searched for.
```

And indeed there was no `Hoobuddy.hs` file.
However building the current master works just fine.
I suggest to re-uploading the current version to hackage.

**Comment by gilligan** [comment]
Ooops, thank you for letting me know. Horribly busy & tired right now but i will fix that asap. Cheers!
PS: this was my first bit of usable haskell code. If you can think of ways to make it (more) useful, let me know :)

**Comment by gilligan** [comment]
Oops.. the cabal file was missing an other-modules statement.
Uploaded new version  0.1.0.1 to hackage and set the other one to deprecated.
